### ISSUE TITLE
Lead Developer Has a Skill Issue

### ISSUE THREAD

**Issue by asc-12** [itsmichaelyu/cardFlashBugs#2]
**Describe the bug**
The lead developer, Michael Yu, sucks at everything and can't even make a flashcard app properly.

**To Reproduce**
1. Use it for 5 minutes and the shittiness will be clear.

**Expected behavior**
A competent app.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Oxygen OS 11.0.9.1.GM21AA
 - Version: 0.1.1
 - Beta: Yes

**Additional context**
Stop shilling signal you fat fuck

**Comment by itsmichaelyu** [comment]
Fixed in 0.1.2. Please update
